server:
  port: 8888

cas:
  server-url-prefix: https://java1234.com:8443/cas
  server-login-url: https://java1234.com:8443/cas/login
  client-host-url: http://java1234.com:8888
  validation-type: cas3
